language: objective-c
osx_image: xcode8.3
xcode_project: FlyveMDMInventory.xcodeproj
xcode_scheme: FlyveMDMInventory
install:
  - "./ci/install.sh"
script:
  - "./ci/script.sh"
after_success:
  - "./ci/deploy.sh"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  global:
  - APPNAME="FlyveMDMInventory"
  - GH_USER=flyve-mdm-bot
  